###########
# site.url, site.title
title: 'Authority to Operate (ATO) Dashboard'
branch: gh-pages

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
baseurl: /ATOdashboard
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

safe: false

collections:
  controls:
    output: true
    permalink: /controls/:path/
  system:
    output: true
    layout: default
    permalink: /system/:path/
